### ISSUE TITLE
Tag releases so it's installable with semver.

### ISSUE THREAD

**Issue by Celc** [matthewhudson/device.js#70]
If you look at `bower info devicejs` compares to `bower info underscore` you'll notice there's no available versions. You need to do `git push origin v0.1.16` or similar (see: http://bob.yexley.net/creating-and-maintaining-your-own-bower-package/)

Currently we have to pin our packages to a commit hash.

**Comment by matthewhudson** [comment]
@Celc @catkins This is part of my general workflow going forward, and should be officially resolve as of [v0.2.2](https://github.com/matthewhudson/device.js/releases/tag/v0.2.2)
