### ISSUE TITLE
wrong version and tag

### ISSUE THREAD

**Issue by PeterDaveHello** [matthewhudson/device.js#71]
bumped to v0.1.61 here,
https://github.com/matthewhudson/device.js/commit/ddc617e8675780afd943632c44c77dc69551c742
but have v0.1.16 here
https://github.com/matthewhudson/device.js/releases
https://github.com/matthewhudson/device.js/tags

**Comment by matthewhudson** [comment]
@PeterDaveHello  Should be resolved as of [v0.2.1](https://github.com/matthewhudson/device.js/releases/tag/v0.2.1)

@megawac I don't own the NPM repo, but I'm working on resolving the naming issue right now.
