### ISSUE TITLE
Orientation wrongly detected (to landscape) when Debug Console is ON

### ISSUE THREAD

**Issue by AlaNDGT** [matthewhudson/device.js#73]
Reproduced on iphone 3gs's Safari browser.

While in portrait orientation and if debug console is on the library detect it as landscape.

**Comment by fabioDMFerreira** [comment]
The "orientationchange" event is dispatched before the rendering. After the event has been dispatched, the browser has to do an animation and render the page.

The next solution is not perfect but solves the problem:
https://stackoverflow.com/questions/9929368/how-do-i-get-the-new-dimensions-of-an-element-after-it-resizes-due-to-a-screen
