### ISSUE TITLE
Cordova application - Object doesn't support property or method

### ISSUE THREAD

**Issue by maxaud** [matthewhudson/device.js#83]
I get this error in a cordova application:

    Unhandled exception at line 97, column 5 in ms-appx://<my_apps_path>/www/js/util/device.js
    0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'tablet'

This is being ran on a Microsoft Surface tablet and my desktop PC. using the `.desktop()` method.

I'm using `device.noConflict();` so it doesn't interfere with the window.device that cordova uses.

**Comment by matthewhudson** [comment]
@maxaud This is a known implementation bug, pushing a fix now.

**Comment by matthewhudson** [comment]
@maxaud Should be resolved as of [v0.2.1](https://github.com/matthewhudson/device.js/releases/tag/v0.2.1)

**Comment by maxaud** [comment]
Wow, you're quick! Thanks a lot!
