### ISSUE TITLE
Das Objekt unterstützt die Eigenschaft oder Methode "trim" nicht

### ISSUE THREAD

**Issue by crazyx13th** [matthewhudson/device.js#94]
Hi there,

ther are problems with the nice IE8:
https://msdn.microsoft.com/de-de/library/ie/ff679971%28v=vs.94%29.aspx
http://stackoverflow.com/questions/2308134/trim-in-javascript-not-working-in-ie

Thx!

Cya
CrazyX13th

**Comment by matthewhudson** [comment]
@crazyx13th Thank you for reporting this - fixed as of v0.2.7
